variable "nsx_manager" {}
variable "nsx_username" {}
variable "nsx_password" {}
variable "sddc_manager" {}
variable "m01_vcenter" {}
variable "m01_nsx_manager_a" {}
variable "m01_nsx_manager_b" {}
variable "m01_nsx_manager_c" {}
variable "w01_vcenter" {}
variable "w01_nsx_manager_a" {}
variable "w01_nsx_manager_b" {}
variable "w01_nsx_manager_c" {}
variable "icmp_all" {}
variable "dns_tcp" {}
variable "dns_udp" {}
variable "dhcp_server" {}
variable "activdir" {}
variable "https" {}
variable "http" {}
variable "ftp" {}
variable "ldap" {}
variable "ldap_udp" {}
variable "ldaps" {}
variable "ssh" {}
variable "syslog_udp" {}
variable "syslog_tcp" {}
variable "snmp" {}
variable "ntp" {}
variable "rdp" {}
variable "tcp_902" {}
variable "udp_902" {}
variable "tcp_9000_9100" {}
variable "tcp_9087" {}
variable "tcp_9084" {}
variable "update_manager" {}
variable "cxt_activdir" {}
variable "cxt_ldap" {}
variable "cxt_dns" {}
variable "cxt_ssl" {}
variable "cxt_ssh" {}
variable "cxt_dcerpc" {}
variable "vm_management_dvpg" {}
variable "aria_x_ans" {}
variable "aria_ans" {}
variable "smtp" {}
variable "smtp_tls" {}
variable "m01_ssp_dvpg" {}
variable "w01_ssp_dvpg" {}
variable "m01_sspi_vm" {}
variable "w01_sspi_vm" {}

